name: "Pipeline: Release"
name: "Pipeline: Release"
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest code
        uses: actions/checkout@v5

      - name: Download dependencies
        run: go mod download

      - name: Build plugin
        run: GOOS=wasip1 GOARCH=wasm go build -buildmode=c-shared -o plugin.wasm plugin.go

      - name: Create packate
        run: zip listenbrainz-daily-playlist.ndp plugin.wasm manifest.json README.md LICENSE.md

      - name: Generate draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: listenbrainz-daily-playlist.ndp
          generate_release_notes: true