name: "Pipeline: Release"
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest code
        uses: actions/checkout@v7

      - name: Install tinygo and dependencies
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.42.0/tinygo_0.42.0_amd64.deb
          sudo dpkg -i tinygo_0.42.0_amd64.deb
          sudo apt install -y binaryen

      - name: Download dependencies
        run: go mod download

      - name: Build plugin
        run: make prod

      - name: Generate draft release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: listenbrainz-daily-playlist.ndp
          generate_release_notes: true
